# Generated by Django 3.0.6 on 2020-06-09 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Postcard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dog_img_url', models.CharField(max_length=200)),
                ('author', models.CharField(help_text='Your name (optional)', max_length=200)),
                ('letter', models.TextField(help_text='Write love letter here', max_length=1000)),
                ('approved', models.BooleanField(default=False)),
            ],
        ),
    ]
